from typing import Dict, Any


class EngineContext:
    """
    The shared memory bus of the engine.
    States read from and write to this payload as it gets passed down the chain.
    """

    def __init__(self):
        self.data: Dict[str, Any] = {
            "filepath": None,
            "target_func": None,
            "extracted_node": None,  # Will hold start_byte, end_byte, etc.
            "llm_payload": None,  # The code generated by Theseus
            "errors": [],  # TextGrad loss / compiler errors
            "retry_count": 0,
            "profile": None,  # The active LanguageProfile
        }


class State:
    """
    The Base Entity for the Ariadne FSM.
    Every state in the engine must inherit from this and implement `execute()`.
    """

    def __init__(self, name: str):
        self.name = name

    def enter(self, context: EngineContext):
        """Fires once when the state is activated."""
        print(f"\n--- ENTERING: {self.name} ---")

    def execute(self, context: EngineContext) -> str:
        """
        The core logic loop.
        MUST return the string name of the NEXT state to transition to.
        To halt the engine cleanly, return 'IDLE'.
        """
        raise NotImplementedError(
            "Each specific state must implement its own execute logic."
        )

    def exit(self, context: EngineContext):
        """Fires once right before transitioning to the next state."""
        pass
